version: "3"

services:
  streaming_server:
    build: nginx/
    volumes:
      - ./assets/videos:/usr/local/nginx/html/video:ro
      - ./assets/audio:/usr/local/nginx/html/audio:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html/stat.xsl:/usr/local/nginx/html/stat.xsl
    ports:
      - "1935:1935"
      - "8080:80"
    networks:
      - rtmp_net

  filestream:
    build: filestream/
    volumes:
      - ./assets/videos:/videos:ro
    entrypoint: [
      "ffmpeg", "-re", "-i", "/videos/bbb_sunflower_1080p_60fps_normal.mp4",
      "-vcodec", "copy", "-loop", "-1", "-c:a", "aac", "-b:a", "160k", "-ar",
      "44100", "-strict", "-2", "-f", "flv", "rtmp://streaming_server:1935/stream/hello"]
    depends_on:
      - streaming_server
    networks:
      - rtmp_net

networks:
  rtmp_net:
